### ISSUE TITLE
Tracknames does not work in bop.json

### ISSUE THREAD

**Issue by el0hh** [LukasLichten/acc_csv2bop#1] opened 2024-09-03 10:06 UTC
Hi, while starting acc 1.10.3 and importing bop.json I got many errors like this:
        Bop: carmodel 31 B:14|R:0 for track Hungaroring
==ERR: Track Hungaroring doesn't exist, BoP line is ignored
        Bop: carmodel 31 B:5|R:0 for track Spa
==ERR: Track Spa doesn't exist, BoP line is ignored
        Bop: carmodel 31 B:9|R:0 for track misano
        Bop: carmodel 20 B:-18|R:0 for track Hungaroring

If I rewirite Spa and Hungaroring to spa and hungaroring (lowercase) it works.
Maybe Kunos start to cleanup their mass from the past.

**Comment by LukasLichten** [comment] 2024-09-12 09:38
Ahhhh, I used the tracknames from the setup folders (due to related project, and just expecting it to be the same), but turns out that for multiplayer tracknames are different, specifically all lower case (and ACC won't just sanitize them... like a proper programm).

So I now sourced the list from accservermanager, which (hopefully) works now, but as that doesn't have a bop option (yet) I can't test it.

**Comment by LukasLichten** [comment] 2024-09-15 04:11
I made a new release, [v1.2.2](https://github.com/LukasLichten/acc_csv2bop/releases/tag/v1.2.2), which should resolve the issue.

As such I will close the issue, if the problem is not resolved you can comment under here anyway (or open a new one, not a big deal).

**Closed as completed by LukasLichten** 2024-09-15 04:11 UTC
